feat: stringify dataset column contents during data loading
aws/fmeval pull request #168
Opened 2024-01-11 21:34 UTC by danielezhu

*Issue #, if available:*

*Description of changes:*
Currently, the JSON parsing code extracts raw data from the input dataset using user-provided JMESPath expressions. This raw data can be of any data type, such as booleans, floats, etc.

This PR adds code that converts the raw extracted data into strings, so that the final Ray Dataset that is produced contains only string data.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-12 00:56 UTC, xiaoyi-cheng approved these changes

2024-01-12 03:10 UTC, keerthanvasist approved these changes

2024-01-12 10:23 UTC, lucfra commented
Thanks @danielezhu ! Just got a question. Will this convert any field of the dataset into a string? 
If so, I would strongly recommend against it.
We should only convert fields that are _required_ to be strings by the eval algorithms (most notably input and targets, if present).

2024-01-12 10:24 UTC, lucfra requested changes
Thanks @danielezhu ! Just got a question. Will this convert any field of the dataset into a string?
If so, I would strongly recommend against it.
We should only convert fields that are required to be strings by the eval algorithms (most notably input and targets, if present).

2024-01-12 10:24 UTC, lucfra requested changes
Thanks @danielezhu ! Just got a question. Will this convert any field of the dataset into a string?
If so, I would strongly recommend against it.
We should only convert fields that are required to be strings by the eval algorithms (most notably input and targets, if present).

2024-01-12 10:26 UTC, franluca submitted a review, later dismissed
Thanks @danielezhu ! Just got a question. Will this convert any field of the dataset into a string?
If so, I would strongly recommend against it.
We should only convert fields that are required to be strings by the eval algorithms (most notably input and targets, if present).

2024-01-12 17:22 UTC, danielezhu commented
Luca raised a good point about not casting _every_ column. It is clear why we shouldn't do this if we consider the log probability columns. I will update this PR after Luca sends me the list of columns that should be converted to strings, and those that should not.

2024-01-12 18:22 UTC, lucfra commented
However I have another question. Can in principle be the fields also lists? like having a list of target output(s) ? Or do we prohibit this?

2024-01-19 16:46 UTC, xiaoyi-cheng submitted a review, later dismissed

2024-01-19 18:32 UTC, danielezhu commented on src/fmeval/data_loaders/json_parser.py
>                  assert_condition(
I think this logic is best explained in the docstring `__init__`.

2024-01-19 19:32 UTC, danielezhu commented on src/fmeval/data_loaders/json_parser.py
> +            raise EvalAlgorithmClientError(
Done

2024-01-19 19:35 UTC, xiaoyi-cheng approved these changes

2024-01-19 23:00 UTC, oyangz approved these changes

2024-01-19 23:02 UTC, merged