Add the BERTScore computation to general semantic robustness
aws/fmeval pull request #184
Opened 2024-02-07 17:37 UTC by bilalaws

*Description of changes:*

We add the BERTScore metric to GeneralSemanticRobustness eval. Previously, we only had a single metric Word Error Rate which is not suitable for non-deterministic models -- a syntactic change in the model output leads to non-zero Word Error Rate even if the semantic meaning is the same. BERTScore measures semantic similarity so is a sensible metric for non-deterministic models.

2024-02-16 15:03 UTC, polaschwoebel approved these changes
I approve. We had multiple rounds of offline discussion, no additional comments.

2024-02-19 10:47 UTC, bilalaws commented on src/fmeval/constants.py
> +class BertscoreModels(Enum):
Done.

2024-02-19 11:29 UTC, bilalaws commented on test/unit/eval_algorithms/test_summarization_accuracy.py
>      def test_get_bert_score(self, mock_ray_get, test_case, config):
Done

2024-02-19 15:21 UTC, polaschwoebel approved these changes
No scientific changes since last review.

2024-02-19 18:31 UTC, oyangz requested changes
Could you add a short metric description in the constants [here](https://github.com/aws/fmeval/blob/main/src/fmeval/reporting/constants.py#L168) for reporting?

2024-02-19 21:40 UTC, malhotra18 approved these changes

2024-02-19 21:41 UTC, merged