feat: update implementation of SummarizationAccuracySemanticRobustness to use transform-based approach
aws/fmeval pull request #230
Opened 2024-03-25 19:42 UTC by danielezhu

*Description of changes:*
This PR updates SASR to use `Transform`s and also updates `evaluate_dataset` to take a `Dataset` instead of `DataConfig`. Because of this change, `compute_and_aggregate_metrics` doesn't really need to be a separate function, so I moved its code into `evaluate_dataset`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-25 21:17 UTC, oyangz submitted a review, later dismissed

2024-03-26 05:57 UTC, danielezhu commented on src/fmeval/eval_algorithms/summarization_accuracy.py
> -            eval_output = util.evaluate_dataset(
Note that this PR changes the signature of the `evaluate_dataset` function, hence why the parameters being passed on the left and right don't match.

2024-03-26 19:28 UTC, malhotra18 requested changes

2024-03-26 19:28 UTC, malhotra18 commented on devtool
> +   pytest -vvv test/integration/test_summarization_accuracy.py test/integration/test_summarization_accuracy_semantic_robustness.py
missed to revert this

2024-03-26 19:28 UTC, malhotra18 commented on src/fmeval/eval_algorithms/general_semantic_robustness.py
> +                pipeline=self.build_pipeline(model, dataset_prompt_template, is_deterministic=is_deterministic),
reminder to make this private method

2024-03-26 20:11 UTC, keerthanvasist approved these changes

2024-03-26 22:31 UTC, closed without merging