fix: Context precision score computation
aws/fmeval pull request #299
Opened 2024-06-27 01:48 UTC by awsvmaringa

*Description of changes:*
This code: `denominator = sum(model_verdicts) + 1e-10` will lead to inaccurate context precision score when `sum(model_verdicts) > 0` and `numerator > 0`. For example: `1 / (1 + 1e-10) = 0.9999999999`
Fixed this by returning `0` if `sum(model_verdicts)` is `0`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-27 01:49 UTC, xiaoyi-cheng requested changes
Please add a unit test to cover this. Thanks!

2024-06-27 16:29 UTC, oyangz commented
Looks good, could you run the linter with `./devtool lint`? It will reformat the files so the lint check tests pass.

2024-06-28 16:05 UTC, oyangz approved these changes

2024-06-30 21:20 UTC, xiaoyi-cheng approved these changes

2024-06-30 21:20 UTC, merged