feat: update context to take lists and rename context field
aws/fmeval pull request #305
Opened 2024-07-10 16:00 UTC by oyangz

*Issue #, if available:*

*Description of changes:*
* Uses Lists of strings instead of string delimiters for multiple contexts since the [Ray dataset issue](https://github.com/ray-project/ray/issues/39559) with Lists has been resolved.
* Rename the context field to `context` as we are merging `target_context` and `retrieved_context` for RAG evaluations.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-10 16:29 UTC, xiaoyi-cheng approved these changes
lgtm!

2024-07-11 19:12 UTC, xiaoyi-cheng commented
Related CR: https://github.com/aws/fmeval/pull/266

2024-07-12 16:16 UTC, xiaoyi-cheng requested changes

2024-07-12 16:16 UTC, xiaoyi-cheng commented on src/fmeval/constants.py
> +    CONTEXT = Column(name="context", should_cast=True)
Please use "Contexts" instead as it will be a list.

2024-07-12 16:21 UTC, xiaoyi-cheng approved these changes

2024-07-12 19:56 UTC, danielezhu approved these changes

2024-07-12 19:56 UTC, merged